namespace: fineract
deployment_name: lms-v2

replicaCount: 1

Labels:
  app: lms-v2

nodeSelector: {}

image:
  repository: "lms-v2-fe"
  tag: "lms-v2"
  pullPolicy: IfNotPresent

configMap:
  data:
    FINERACT_NODE_ID: "1"
    FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
    FINERACT_HIKARI_JDBC_URL: "jdbc:mysql://pre-prod-lending.c1z93jsyca9u.ap-south-1.rds.amazonaws.com:3306/fineract_tenants?serverTimezone=UTC"
    FINERACT_DEFAULT_TENANTDB_HOSTNAME: "pre-prod-lending.c1z93jsyca9u.ap-south-1.rds.amazonaws.com"
    FINERACT_DEFAULT_TENANTDB_PORT: "3306"
    FINERACT_DEFAULT_TENANTDB_NAME: "fineract_default"
    FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "default"
    FINERACT_USER: "1000"
    FINERACT_GROUP: "1000"
    FINERACT_HIKARI_MINIMUM_IDLE: "3"
    FINERACT_HIKARI_MAXIMUM_POOL_SIZE: "10"
    FINERACT_HIKARI_IDLE_TIMEOUT: "60000"
    FINERACT_HIKARI_CONNECTION_TIMEOUT: "20000"
    FINERACT_HIKARI_TEST_QUERY: "SELECT 1"
    FINERACT_HIKARI_AUTO_COMMIT: "true"
    FINERACT_HIKARI_DS_PROPERTIES_CACHE_PREP_STMTS: "true"
    FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SIZE: "250"
    FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SQL_LIMIT: "2048"
    FINERACT_HIKARI_DS_PROPERTIES_USE_SERVER_PREP_STMTS: "true"
    FINERACT_HIKARI_DS_PROPERTIES_USE_LOCAL_SESSION_STATE: "true"
    FINERACT_HIKARI_DS_PROPERTIES_REWRITE_BATCHED_STATEMENTS: "true"
    FINERACT_HIKARI_DS_PROPERTIES_CACHE_RESULT_SET_METADATA: "true"
    FINERACT_HIKARI_DS_PROPERTIES_CACHE_SERVER_CONFIGURATION: "true"
    FINERACT_HIKARI_DS_PROPERTIES_ELIDE_SET_AUTO_COMMITS: "true"
    FINERACT_HIKARI_DS_PROPERTIES_MAINTAIN_TIME_STATS: "false"
    FINERACT_HIKARI_DS_PROPERTIES_LOG_SLOW_QUERIES: "true"
    FINERACT_HIKARI_DS_PROPERTIES_DUMP_QUERIES_IN_EXCEPTION: "true"
    FINERACT_DEFAULT_TENANTDB_CONN_PARAMS: ""
    FINERACT_DEFAULT_TENANTDB_TIMEZONE: "Asia/Kolkata"
    FINERACT_DEFAULT_TENANTDB_DESCRIPTION: "Default Demo Tenant"
    FINERACT_DEFAULT_MASTER_PASSWORD: "fineract"
    FINERACT_MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
    FINERACT_MANAGEMENT_METRICS_TAGS_APPLICATION: "fineract"
    FINERACT_REMOTE_JOB_MESSAGE_HANDLER_SPRING_EVENTS_ENABLED: "true"
    FINERACT_INSECURE_HTTP_CLIENT: "true"
    SPRING_PROFILES_ACTIVE: "test,diagnostics"
    JAVA_TOOL_OPTIONS: "-Dserver.ssl.enabled=false"
    OTEL_SERVICE_NAME: "fineract"

secret:
  enabled: true
  data:
    FINERACT_HIKARI_USERNAME: "fineract_user"
    FINERACT_HIKARI_PASSWORD: "F!N3R4CT_U53R"
    FINERACT_DEFAULT_TENANTDB_UID: "fineract_user"
    FINERACT_DEFAULT_TENANTDB_PWD: "F!N3R4CT_U53R"

service:
  type: ClusterIP
  port: 8443

serviceAccount:
  create: false
  name: "admin"
  annotations: {}

healthcheck:
  enabled: false

resources: {}

autoscaling:
  enabled: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
